# Generated by Django 3.0.7 on 2020-06-24 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Tytuł')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Tło')),
                ('body', tinymce.models.HTMLField(verbose_name='Treść')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('method', models.CharField(choices=[('SIMPLE', 'Simple'), ('COMPLEX', 'Complex')], default='COMPLEX', max_length=7)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('joined', models.ManyToManyField(blank=True, related_name='joinedtogoal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
