# Generated by Django 3.0.7 on 2020-06-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateField(verbose_name='Początek')),
                ('end_at', models.DateField(verbose_name='Koniec')),
                ('slug', models.SlugField(max_length=255)),
                ('days', models.TextField(default='')),
            ],
        ),
    ]
