# Generated by Django 2.1.5 on 2020-07-07 08:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateField(blank=True, null=True, verbose_name='Początek')),
                ('end_at', models.DateField(blank=True, null=True, verbose_name='Koniec')),
                ('slug', models.SlugField(max_length=255)),
                ('days', models.TextField(default='')),
                ('dayslist', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='datelist',
            name='datelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SimpleHabitTracker.Habit'),
        ),
    ]
