# Generated by Django 2.1.5 on 2020-07-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleHabitTracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datelist',
            name='datelist',
        ),
        migrations.DeleteModel(
            name='DateList',
        ),
    ]
