# Generated by Django 2.1.5 on 2020-07-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleHabitTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='end_at',
            field=models.DateField(blank=True, null=True, verbose_name='Koniec'),
        ),
    ]
