# Generated by Django 2.1.5 on 2020-07-06 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleHabitTracker', '0002_auto_20200706_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleHabitTracker.Habit')),
            ],
        ),
    ]
