# Generated by Django 2.1.5 on 2020-07-06 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleHabitTracker', '0003_datelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datelist',
            name='datelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SimpleHabitTracker.Habit'),
        ),
    ]
