# Generated by Django 2.1.5 on 2020-07-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleHabitTracker', '0004_auto_20200706_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_at',
            field=models.DateField(blank=True, null=True, verbose_name='Początek'),
        ),
    ]
